function throwError(error, params)
	
end


-- CREATE ERROR TASK